### ISSUE TITLE
Documentation discrepancy

### ISSUE THREAD

**Issue by juhalehtonen** [jaamo/restfight#9]
Currently the Swagger documentation for the status endpoint says that the robot_id parameter should be a string, but the game seems to always generate the robot_id as an integer.

Docs: https://app.swaggerhub.com/apis/jaamo/RESTFight/1.0.0#/default/gameStatus
Code: https://github.com/jaamo/restfight/blob/66e6a8bbc7c3ac4348dfdc4bd4241d33c3c87a33/restfight/structures.go#L13

**Comment by jaamo** [comment]
At the moment robot_id is just a timestamp but in the future it might be something more complicated. So I'm keeping it as string for future purposes :)
